#======== Section 01, Input data
Files:
  InputCatalogFileName: "DB/Golestan.out"
#======== Section 02, Study region
Region:
  CentralLat: 37.00
  CentralLon: 55.00
  Radius: 400.0
  RegionName: "EAlborz"
#======== Section 02, Velocity Model
VelocityModel:
  Pvel: [5.90, 6.15, 6.20, 6.30, 6.35, 8.00, 8.20]
  Deps: [0.00, 5.00, 10.0, 20.0, 33.0, 42.0, 70.0]
  VpVs: 1.73
#======== Section 03, Visulization
Figures:
  EventsMaxDepth: 30