#======== Section 01, Input data
Files:
  InputCatalogFileName: "DB/2021_2024.out"
#======== Section 02, Study region
Region:
  CentralLat: 36.00
  CentralLon: 52.00
  Radius: 300.0
  RegionName: "CAlborz"
#======== Section 02, Velocity Model
VelocityModel:
  Pvel: [5.35, 5.80, 6.00, 6.15, 6.40, 8.0]
  Deps: [0.0, 6.0, 10.5, 16.0, 22.5, 56.0]
  VpVs: 1.73
#======== Section 03, Visulization
Figures:
  EventsMaxDepth: 30